"""The verified source inventory (from the internet-research pass).

Every entry mirrors what was actually fetched and confirmed: real indexes,
RSS/Atom feeds, and documented JSON APIs with real query patterns. Selectors
are best-effort and the collectors degrade gracefully if a site changes — a
broken selector yields no leads, never a crash.

Spec kinds:
  rss        Atom/RSS feed; leads come from entries (title/link/summary).
  index      HTML list pages (category/tag/archive); leads come from <a> tags,
             optionally followed by a full-text fetch of the article body.
  api        JSON endpoint with typed response mapping (archive.org, loc.gov,
             Wellcome).
  mediawiki  MediaWiki API (categorymembers) or a Wikipedia page whose links
             are harvested (Wikipedia:Unusual_articles).
"""
from __future__ import annotations

SOURCES = [
    # -------------------------------------------------------- war_news
    {
        "key": "isw",
        "name": "ISW Iran Update",
        "kind": "index",
        "niche": "war_news",
        "starts": ["https://understandingwar.org/research/middle-east/iran-update/"],
        "link_match": ["iran-update"],
        "exclude": ["/analysis/", "#", "linkedin.com", "twitter.com", "facebook.com", "reddit.com", "intent/"],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 6,
        "body_selectors": [".field--name-body", ".body", ".content", "article"],
    },
    {
        "key": "ctp",
        "name": "Critical Threats Project",
        "kind": "index",
        "niche": "war_news",
        "starts": ["https://www.criticalthreats.org/analysis/"],
        "link_match": ["iran-update"],
        "exclude": ["#"],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 4,
        "body_selectors": [".field--name-body", ".node-content", "article"],
    },
    {
        "key": "usni",
        "name": "U.S. Naval Institute News",
        "kind": "rss",
        "niche": "war_news",
        "starts": ["https://news.usni.org/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".entry-content", ".td-post-content", "article"],
    },
    {
        "key": "centcom",
        "name": "U.S. Central Command Public Releases",
        "kind": "index",
        "niche": "war_news",
        "starts": ["https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/"],
        "link_match": ["/MEDIA/PUBLIC-RELEASES/Article/"],
        "exclude": ["#"],
        "paginate": "?Page={n}",
        "max_pages": 1,
        "fetch_articles": 4,
        "body_selectors": [".field--name-body", ".field-name-body", "article"],
    },
    {
        "key": "lwj",
        "name": "FDD's Long War Journal",
        "kind": "rss",
        "niche": "war_news",
        "starts": ["https://www.longwarjournal.org/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".entry-content", ".node-content", "article"],
    },
    # ------------------------------------------------------ war_history
    {
        "key": "mhn",
        "name": "Military History Now",
        "kind": "rss",
        "niche": "war_history",
        "starts": ["https://militaryhistorynow.com/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".entry-content", "article"],
    },
    {
        "key": "historynet",
        "name": "HistoryNet",
        "kind": "rss",
        "niche": "war_history",
        "starts": ["https://historynet.com/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".entry-content", "article"],
    },
    {
        "key": "whonline",
        "name": "War History Online",
        "kind": "index",
        "niche": "war_history",
        "starts": ["https://www.warhistoryonline.com/category/history/"],
        "link_match": ["warhistoryonline.com/"],
        "exclude": ["/category/", "/about", "/contact", "/legal", "/privacy", "/terms", "#"],
        "paginate": "page/{n}/",
        "max_pages": 2,
        "fetch_articles": 3,
        "body_selectors": [".entry-content", ".wpb_text_column", "article"],
    },
    {
        "key": "cmh",
        "name": "U.S. Army Center of Military History",
        "kind": "index",
        "niche": "war_history",
        "starts": ["https://history.army.mil/Publications/Publications-Catalog/"],
        "link_match": ["/Publications/Publications-Catalog/"],
        "exclude": ["#"],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".content", "article"],
    },
    # ------------------------------------------------------ experiments
    {
        "key": "pwct",
        "name": "Pacific War Crimes Trials Digital Archive",
        "kind": "index",
        "niche": "experiments",
        "starts": ["https://pwct.law.virginia.edu/collections/"],
        "link_match": ["pwct.law.virginia.edu/collections/", "pwct.law.virginia.edu/node/"],
        "exclude": ["#"],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".content", "article"],
    },
    {
        "key": "wellcome",
        "name": "Wellcome Collection Catalogue",
        "kind": "api",
        "niche": "experiments",
        "starts": ["https://api.wellcomecollection.org/catalogue/v2/works"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [],
        "api_params": [
            {"query": "human experimentation", "pageSize": 25},
            {"query": "human radiation experiments", "pageSize": 25},
            {"query": "vivisection history", "pageSize": 25},
        ],
        "api_items": "results",
        "api_map": {
            "title": "title",
            "url": ("id", "https://wellcomecollection.org/works/{id}"),
            "summary": "description",
            "date": "production.date",
        },
        "api_rows": 25,
    },
    {
        "key": "loc",
        "name": "Library of Congress (Chronicling America)",
        "kind": "api",
        "niche": "experiments",
        "starts": ["https://www.loc.gov/search/"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [],
        "api_params": [
            {"q": "human experimentation", "fo": "json", "c": 40},
            {"q": "military medical experiments", "fo": "json", "c": 40},
            {"q": "vivisection subjects", "fo": "json", "c": 40},
        ],
        "api_items": "results",
        "api_map": {
            "title": "title",
            "url": ("url", "{url}"),
            "summary": "description",
            "date": "date",
        },
        "api_rows": 40,
    },
    {
        "key": "archiveorg",
        "name": "Internet Archive",
        "kind": "api",
        "niche": "experiments",
        "starts": ["https://archive.org/advancedsearch.php"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [],
        "api_params": [
            {"q": 'subject:"Unit 731"', "rows": 25, "fl": "identifier,title,description,date", "output": "json"},
            {"q": "biological warfare human experiments", "rows": 25, "fl": "identifier,title,description,date", "output": "json"},
            {"q": "Khabarovsk trial", "rows": 25, "fl": "identifier,title,description,date", "output": "json"},
        ],
        "api_items": "response.docs",
        "api_map": {
            "title": "title",
            "url": ("identifier", "https://archive.org/details/{identifier}"),
            "summary": "description",
            "date": "date",
        },
        "api_rows": 25,
    },
    # ------------------------------------------------------ dark_history
    {
        "key": "wiki_cats",
        "name": "Wikipedia: experiment categories",
        "kind": "mediawiki",
        "niche": "experiments",
        "starts": [
            "Category:Human_subject_research",
            "Category:Biological_warfare",
            "Category:Bioethics",
        ],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [],
    },
    {
        "key": "wiki_dark",
        "name": "Wikipedia: dark-history categories",
        "kind": "mediawiki",
        "niche": "dark_history",
        "starts": [
            "Category:Japanese_war_crimes",
            "Category:German_war_crimes",
            "Category:Crimes_against_humanity",
            "Category:History_of_medicine",
            "Category:Medical_ethics_scandals",
        ],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [],
    },
    {
        "key": "listverse",
        "name": "Listverse",
        "kind": "rss",
        "niche": "dark_history",
        "starts": ["https://listverse.com/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".entry-content", "article"],
    },
    {
        "key": "damninteresting",
        "name": "Damn Interesting",
        "kind": "rss",
        "niche": "dark_history",
        "starts": ["https://www.damninteresting.com/feed"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".article-body", "article"],
    },
    {
        "key": "atlasobscura",
        "name": "Atlas Obscura",
        "kind": "index",
        "niche": "dark_history",
        "starts": [
            "https://www.atlasobscura.com/categories/medical-experiments",
            "https://www.atlasobscura.com/categories/dissection",
        ],
        "link_match": ["atlasobscura.com/articles/", "atlasobscura.com/places/"],
        "exclude": ["/categories/", "#", "atlasobscura.com/users/", "/places/new", "all-places-in-the-atlas-on-one-map"],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 2,
        "body_selectors": [".article-body", ".place-category-facts", "article"],
    },
    {
        "key": "shi",
        "name": "Science History Institute Digital Collections",
        "kind": "rss",
        "niche": "dark_history",
        "starts": ["https://digital.sciencehistory.org/catalog.atom"],
        "link_match": [],
        "exclude": [],
        "paginate": None,
        "max_pages": 1,
        "fetch_articles": 0,
        "body_selectors": [".content", "article"],
    },
]

# Per-source authority used by the scorer (0..1). Primary sources and major
# analysts rank highest; listicle aggregators rank lowest.
AUTHORITY = {
    "isw": 1.0,
    "ctp": 1.0,
    "centcom": 1.0,
    "usni": 1.0,
    "lwj": 0.9,
    "cmh": 1.0,
    "mhn": 0.85,
    "historynet": 0.85,
    "whonline": 0.8,
    "pwct": 1.0,
    "wellcome": 0.9,
    "loc": 0.9,
    "archiveorg": 0.85,
    "wiki_cats": 0.7,
    "wiki_dark": 0.7,
    "listverse": 0.6,
    "damninteresting": 0.9,
    "atlasobscura": 0.75,
    "shi": 0.85,
}

TTL_HOURS = {
    "rss": 6,
    "index": 6,
    "api": 12,
    "mediawiki": 24,
}


def spec_ttl_hours(spec: dict) -> float:
    return TTL_HOURS.get(spec.get("kind", "index"), 6) * 3600